'use strict';
// Token state is independent of the UI; CSS generation is shared by preview and export.
const DEFAULTS = Object.freeze({primary:'#635bff',textColor:'#20232b',background:'#f5f6f8',fontFamily:'system',fontSize:16,fontWeight:'400',lineHeight:'1.6',buttonRadius:8,buttonSize:'medium',hoverEffect:'lift',cardRadius:16,shadow:'soft',borderWidth:'1',spacing:24});
const FONTS={system:'system-ui, -apple-system, "Segoe UI", sans-serif',sans:'Arial, "Malgun Gothic", sans-serif',serif:'Georgia, "Times New Roman", serif',mono:'"SFMono-Regular", Consolas, monospace'};
const SHADOWS={none:'none',soft:'0 4px 20px rgba(20, 24, 40, 0.04)',medium:'0 8px 24px rgba(20, 24, 40, 0.10)',deep:'0 16px 40px rgba(20, 24, 40, 0.18)'};
const SIZES={small:'8px 14px',medium:'11px 18px',large:'15px 24px'};
const STORAGE_KEY='style-forge.projects.v1';
let state={...DEFAULTS}, codeTab='all', savedSnapshot='', toastTimer;
const $=id=>document.getElementById(id);
const previewStyle=document.createElement('style');document.head.append(previewStyle);
function contrast(hex){const rgb=hex.slice(1).match(/../g).map(c=>{const v=parseInt(c,16)/255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4});return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722>.179?'#111111':'#ffffff'}
function generateCSS(s){
 const tokens=`/* STYLE FORGE · 디자인 토큰 */\n:root {\n  --sf-primary: ${s.primary};\n  --sf-on-primary: ${contrast(s.primary)};\n  --sf-text: ${s.textColor};\n  --sf-background: ${s.background};\n  --sf-font-family: ${FONTS[s.fontFamily]};\n  --sf-font-size: ${s.fontSize}px;\n  --sf-font-weight: ${s.fontWeight};\n  --sf-line-height: ${s.lineHeight};\n  --sf-button-radius: ${s.buttonRadius}px;\n  --sf-button-padding: ${SIZES[s.buttonSize]};\n  --sf-card-radius: ${s.cardRadius}px;\n  --sf-card-shadow: ${SHADOWS[s.shadow]};\n  --sf-border-width: ${s.borderWidth}px;\n  --sf-spacing: ${s.spacing}px;\n}`;
 const hover=s.hoverEffect==='lift'?'transform: translateY(-2px);\n  box-shadow: 0 5px 14px color-mix(in srgb, var(--sf-primary) 25%, transparent);':s.hoverEffect==='darken'?'filter: brightness(0.9);':'transform: none;';
 const components=`/* STYLE FORGE · 컴포넌트 */\n.sf-button {\n  display: inline-flex;\n  align-items: center;\n  justify-content: center;\n  gap: 8px;\n  padding: var(--sf-button-padding);\n  border: 1px solid transparent;\n  border-radius: var(--sf-button-radius);\n  background: var(--sf-primary);\n  color: var(--sf-on-primary);\n  font-family: var(--sf-font-family);\n  font-size: var(--sf-font-size);\n  font-weight: var(--sf-font-weight);\n  line-height: var(--sf-line-height);\n  cursor: pointer;\n  transition: transform .2s, filter .2s, box-shadow .2s;\n}\n\n.sf-button:hover:not(:disabled) {\n  ${hover}\n}\n\n.sf-button--secondary {\n  background: transparent;\n  color: var(--sf-primary);\n  border-color: var(--sf-primary);\n}\n\n.sf-button:disabled {\n  opacity: .35;\n  cursor: not-allowed;\n}\n\n.sf-button:focus-visible,\n.sf-input:focus-visible {\n  outline: 2px solid var(--sf-primary);\n  outline-offset: 3px;\n}\n\n.sf-card {\n  box-sizing: border-box;\n  padding: var(--sf-spacing);\n  background: #ffffff;\n  color: var(--sf-text);\n  border: var(--sf-border-width) solid #e5e7eb;\n  border-radius: var(--sf-card-radius);\n  box-shadow: var(--sf-card-shadow);\n  font-family: var(--sf-font-family);\n  font-size: var(--sf-font-size);\n  font-weight: var(--sf-font-weight);\n  line-height: var(--sf-line-height);\n}\n\n.sf-badge {\n  display: inline-block;\n  padding: 3px 8px;\n  border-radius: 4px;\n  background: color-mix(in srgb, var(--sf-primary) 8%, white);\n  color: var(--sf-primary);\n  font-size: .65em;\n}\n\n.sf-input {\n  box-sizing: border-box;\n  width: 100%;\n  min-width: 0;\n  padding: 10px 12px;\n  border: 1px solid #e5e7eb;\n  border-radius: var(--sf-button-radius);\n  background: #ffffff;\n  color: var(--sf-text);\n  font: inherit;\n  font-size: .75em;\n}\n\n@media (prefers-reduced-motion: reduce) {\n  .sf-button { transition: none; }\n}`;
 return {tokens,components,all:tokens+'\n\n'+components+'\n'};
}
function snapshot(){return JSON.stringify({name:$('project-name').value.trim(),tokens:state})}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3000)}
function render(){const css=generateCSS(state);previewStyle.textContent=css.all;$('generated-code').textContent=css[codeTab];$('line-count').textContent=css[codeTab].split('\n').length+' 줄';$('primary-hex').value=state.primary.toUpperCase();$('primary-hex').setCustomValidity('');for(const id of ['fontSize','buttonRadius','cardRadius','spacing'])$(id+'-value').textContent=state[id]+' px';$('palette').replaceChildren(...[85,65,40,15,0].map(light=>{const el=document.createElement('span');el.style.background=light?`color-mix(in srgb, ${state.primary} ${100-light}%, white)`:state.primary;return el}));$('token-strip').replaceChildren(...[`Color ${state.primary.toUpperCase()}`,`Radius ${state.cardRadius}px`,`Space ${state.spacing}px`,`Type ${state.fontSize}px`].map(t=>{const el=document.createElement('span');el.textContent=t;return el}));$('save-state').textContent=snapshot()===savedSnapshot?'변경사항 저장됨':'저장되지 않음'}
function syncControls(){for(const key of Object.keys(DEFAULTS))$(key).value=state[key];render()}
function validatedTokens(raw){if(!raw||typeof raw!=='object')throw Error('잘못된 프로젝트 데이터');const s={...DEFAULTS};for(const key of Object.keys(s)){const v=raw[key],el=$(key);if(el.type==='color'){if(typeof v==='string'&&/^#[0-9a-f]{6}$/i.test(v))s[key]=v.toLowerCase()}else if(el.type==='range'){if(Number.isFinite(Number(v)))s[key]=Math.min(Number(el.max),Math.max(Number(el.min),Math.round(Number(v))))}else if([...el.options].some(o=>o.value===String(v)))s[key]=String(v)}return s}
function readProjects(){const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');if(!Array.isArray(raw))throw Error('저장 형식 오류');return raw.filter(p=>p&&typeof p.id==='string'&&typeof p.name==='string'&&p.tokens)}
function refreshProjects(selected=''){try{const projects=readProjects();$('saved-projects').replaceChildren(new Option('저장된 프로젝트', ''),...projects.map(p=>new Option(p.name,p.id)));$('saved-projects').value=selected}catch{toast('저장소를 읽을 수 없습니다. 브라우저 저장 설정을 확인하세요.')}}
$('settings-form').addEventListener('submit',e=>e.preventDefault());
$('settings-form').addEventListener('input',e=>{const key=e.target.id;if(key==='primary-hex'){if(/^#[0-9a-f]{6}$/i.test(e.target.value)){state.primary=e.target.value.toLowerCase();$('primary').value=state.primary;render()}else e.target.setCustomValidity('#와 6자리 HEX 값을 입력하세요.');return}if(Object.hasOwn(DEFAULTS,key)){state[key]=e.target.type==='range'?Number(e.target.value):e.target.value;render()}});
$('primary-hex').addEventListener('change',e=>{if(!/^#[0-9a-f]{6}$/i.test(e.target.value)){toast('색상은 #635BFF처럼 6자리 HEX로 입력하세요.');render()}});
$('project-name').addEventListener('input',render);
$('reset').addEventListener('click',()=>{state={...DEFAULTS};syncControls();toast('디자인 설정을 초기화했습니다.')});
$('save-project').addEventListener('click',()=>{const name=$('project-name').value.trim();if(!name){toast('프로젝트 이름을 입력하세요.');$('project-name').focus();return}try{const projects=readProjects();const existing=projects.find(p=>p.id===$('saved-projects').value&&p.name===name)||projects.find(p=>p.name===name);const project={id:existing?.id||crypto.randomUUID(),name,tokens:{...state},updatedAt:new Date().toISOString()};if(existing)projects[projects.indexOf(existing)]=project;else projects.push(project);localStorage.setItem(STORAGE_KEY,JSON.stringify(projects));savedSnapshot=snapshot();refreshProjects(project.id);render();toast('프로젝트를 이 브라우저에 저장했습니다.')}catch{toast('저장하지 못했습니다. 브라우저 저장 공간과 권한을 확인하세요.')}});
$('load-project').addEventListener('click',()=>{try{const project=readProjects().find(p=>p.id===$('saved-projects').value);if(!project){toast('불러올 프로젝트를 선택하세요.');return}state=validatedTokens(project.tokens);$('project-name').value=project.name.slice(0,60);savedSnapshot=snapshot();syncControls();toast('프로젝트를 불러왔습니다.')}catch{toast('프로젝트를 불러오지 못했습니다.')}});
$('delete-project').addEventListener('click',()=>{const id=$('saved-projects').value;if(!id){toast('삭제할 프로젝트를 선택하세요.');return}if(!confirm('저장된 프로젝트를 삭제할까요? 현재 편집 중인 디자인은 유지됩니다.'))return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(readProjects().filter(p=>p.id!==id)));savedSnapshot='';refreshProjects();render();toast('저장된 프로젝트를 삭제했습니다.')}catch{toast('프로젝트를 삭제하지 못했습니다.')}});
for(const button of document.querySelectorAll('[data-device]'))button.addEventListener('click',()=>{document.querySelectorAll('[data-device]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});$('design-preview').classList.toggle('mobile',button.dataset.device==='mobile')});
for(const button of document.querySelectorAll('[data-code]'))button.addEventListener('click',()=>{codeTab=button.dataset.code;document.querySelectorAll('[data-code]').forEach(b=>b.classList.toggle('active',b===button));render()});
async function copyCSS(){const text=generateCSS(state)[codeTab];try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(text);else{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();const success=document.execCommand('copy');area.remove();if(!success)throw Error('copy failed')};toast('CSS를 클립보드에 복사했습니다.')}catch{toast('복사 권한이 없습니다. CSS 다운로드를 이용하세요.')}}
function downloadCSS(){const blob=new Blob([generateCSS(state).all],{type:'text/css;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=($('project-name').value.trim().replace(/[<>:"/\\|?*\x00-\x1f]/g,'-')||'style-forge')+'.css';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('전체 CSS 파일을 다운로드했습니다.')}
for(const id of ['download-top','download-css'])$(id).addEventListener('click',downloadCSS);
for(const id of ['copy-css','copy-icon'])$(id).addEventListener('click',copyCSS);
document.querySelectorAll('[data-demo]').forEach(b=>b.addEventListener('click',()=>toast('미리보기 버튼의 클릭 상태를 확인했습니다.')));
$('sample-form').addEventListener('submit',e=>{e.preventDefault();toast('입력 폼 검증 완료! 미리보기에서는 이메일을 전송하지 않습니다.')});
refreshProjects();syncControls();
